/**
 * Removes the "Notes to Manager" line from a shift post text.
 * The full text (including this line) is always stored in the DB so managers
 * can read it in ShiftHistory. Everywhere else it is shown to front-desk
 * staff this function should be applied first.
 */
export function filterManagerNotes(text) {
  if (!text) return text
  return text
    // New Markdown section (with preceding ---): consume the divider + section so no double --- remains
    .replace(/\n---\n+###[^\n]*Notes to Manager[\s\S]*?(?=\n---|$)/g, '')
    // Old Markdown section (no preceding ---): just the section header + content
    .replace(/\n###[^\n]*Notes to Manager[\s\S]*?(?=\n---|$)/g, '')
    // Legacy bullet/inline formats
    .replace(/\n(?:•\s*)?Notes to Manager:[^\n]*/g, '')
    .trim()
}

/**
 * Returns true when a post_text was generated by the Night Audit form.
 */
export function isNightAuditPost(text) {
  return !!text?.includes('Night Audit Shift Log')
}

/**
 * Parses the Night Audit 3-column table and activity fields from a post_text.
 */
export function parseNightAuditFromPostText(text) {
  if (!text) return {}
  const escape = (label) => label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const get = (...labels) => {
    for (const label of labels) {
      const escaped = escape(label)
      // key: value format
      const m1 = text.match(new RegExp(escaped + ': (.+)', 'm'))
      if (m1) return m1[1].trim()
      // Markdown table: | Label | Value | (strip any surrounding **)
      const m2 = text.match(new RegExp('\\|\\s*' + escaped + '\\s*\\|\\s*([^|\\n]+?)\\s*\\|', 'm'))
      if (m2) return m2[1].trim().replace(/^\*+|\*+$/g, '').trim()
      // **Label:** value on the same line (new inline format)
      const m3 = text.match(new RegExp('\\*\\*' + escaped + ':\\*\\* (.+)', 'm'))
      if (m3) return m3[1].trim()
    }
    return ''
  }
  const getBullets = (afterLabel) => {
    const escaped = escape(afterLabel)
    // New format: **Label:**\n- items
    const m1 = text.match(new RegExp('\\*\\*' + escaped + '(?:[^*]*)\\*\\*[^\n]*\n((?:- [^\n]*\n?)+)'))
    if (m1) return m1[1].trim().split('\n').map(l => l.replace(/^- /, '')).filter(Boolean).join('\n')
    // Legacy: Label:\n• items
    const m2 = text.match(new RegExp(escaped + '(?:: [^\\n]*)?\\n((?:• [^\\n]*\\n?)+)'))
    if (!m2) return ''
    return m2[1].trim().split('\n').map(l => l.replace(/^• /, '')).filter(Boolean).join('\n')
  }
  const getSection = (sectionLabel) => {
    // New Markdown section: ### [...] Label\n[content until --- or ### or end]
    const escaped = escape(sectionLabel)
    const m = text.match(new RegExp('###[^\\n]*' + escaped + '[^\\n]*\\n([\\s\\S]+?)(?=\\n---|\\n###|$)'))
    if (m) return m[1].trim()
    return get(sectionLabel)
  }
  const getTriplet = (label) => {
    const escaped = escape(label)
    // New 4-col table: | Metric | Start | End | **New** |
    const tm = text.match(new RegExp('\\|\\s*' + escaped + '\\s*\\|\\s*([^|\\n]+?)\\s*\\|\\s*([^|\\n]+?)\\s*\\|\\s*\\*{0,2}([^|\\n*]+?)\\*{0,2}\\s*\\|', 'm'))
    if (tm) return { s: tm[1].trim(), e: tm[2].trim(), n: tm[3].trim() }
    // Legacy compact: Label: Start X | End Y | New Z
    const compact = text.match(new RegExp(escaped + ': Start (.*?) \\| End (.*?) \\| New (.*)', 'm'))
    if (compact) return { s: compact[1].trim(), e: compact[2].trim(), n: compact[3].trim() }
    // Legacy verbose: Label (Start Shift): X
    return {
      s: get(`${label} (Start Shift)`),
      e: get(`${label} (Ending Day)`),
      n: get(`${label} (New Business Day)`),
    }
  }
  const occ = getTriplet('Occupancy')
  const adr = getTriplet('ADR')
  const revpar = getTriplet('RevPAR')
  const dep = getTriplet("Today's Departures")
  const arr = getTriplet("Today's Arrivals")
  const pend = getTriplet('Pending Arrivals')
  const avail = getTriplet('Available Rooms')
  const walkin = getTriplet('Walk-In')
  return {
    na_occ_s:       occ.s,
    na_occ_e:       occ.e,
    na_occ_n:       occ.n,
    na_adr_s:       adr.s,
    na_adr_e:       adr.e,
    na_adr_n:       adr.n,
    na_revpar_s:    revpar.s,
    na_revpar_e:    revpar.e,
    na_revpar_n:    revpar.n,
    na_dep_s:       dep.s,
    na_dep_e:       dep.e,
    na_dep_n:       dep.n,
    na_arr_s:       arr.s,
    na_arr_e:       arr.e,
    na_arr_n:       arr.n,
    na_pend_s:      pend.s,
    na_pend_e:      pend.e,
    na_pend_n:      pend.n,
    na_avail_s:     avail.s,
    na_avail_e:     avail.e,
    na_avail_n:     avail.n,
    na_walkin_s:    walkin.s,
    na_walkin_e:    walkin.e,
    na_walkin_n:    walkin.n,
    na_declined:    get('Declined Payments'),
    na_ooo:         get('Out of Order Rooms'),
    na_ooo_detail:  getBullets('Out of Order Room Details'),
    na_walkin_res:  get('Walk-in Reservations'),
    na_gtd_noshow:  get('GTD No-Show'),
    na_cancel_ct:   get('Cancellations'),
    na_cancel_detail: getBullets('Cancellations'),
    na_rate_adj:    get('Rate Adj/Refunds'),
    na_guest_req:        get('Guest Requests'),
    na_guest_req_detail: getBullets('Guest Request Details'),
    na_maint_ct:    get('Maintenance Pass'),
    na_maint_detail: getBullets('Maintenance Pass'),
    na_security:    (() => {
      const raw = get('Security Onsite')
      return raw ? raw.split(' — ')[0].trim() : ''
    })(),
    na_security_name: (() => {
      const raw = get('Security Onsite')
      if (!raw || !raw.includes(' — ')) return ''
      return raw.split(' — ').slice(1).join(' — ').trim()
    })(),
    na_comments:    get('General Comments'),
    na_guest_issues: get('Guest Issues / Incidents / Concerns', 'Guest Issues/Incidents/Concerns'),
    na_high_bal:    get('High Balances'),
    na_callouts:    get('Call Outs'),
    manager_notes:  getSection('Notes to Manager') || get('Notes to Manager'),
    handoff_note:   getSection('Handoff Note for Morning Shift') || getSection('Handoff Note') || get('Handoff Note'),
  }
}

/**
 * Parses the key hotel metrics out of a shift log post_text string.
 * Used both in Checklist (edit/restore) and in HotelSnapshot (dashboard).
 */
export function parseMetaFromPostText(text) {
  if (!text) return {}
  const escape = (label) => label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const get = (...labels) => {
    for (const label of labels) {
      const escaped = escape(label)
      // key: value format
      const m1 = text.match(new RegExp(escaped + ': (.+)', 'm'))
      if (m1) return m1[1].trim()
      // Markdown table: | Label | Value |
      const m2 = text.match(new RegExp('\\|\\s*' + escaped + '\\s*\\|\\s*([^|\\n]+?)\\s*\\|', 'm'))
      if (m2) return m2[1].trim().replace(/^\*+|\*+$/g, '').trim()
      // **Label:** value
      const m3 = text.match(new RegExp('\\*\\*' + escaped + ':\\*\\* (.+)', 'm'))
      if (m3) return m3[1].trim()
    }
    return ''
  }
  const getBullets = (afterLabel) => {
    const escaped = escape(afterLabel)
    const m = text.match(new RegExp(escaped + '(?:: [^\\n]*)?\\n((?:• [^\\n]*\\n?)+)'))
    if (!m) return ''
    return m[1].trim().split('\n').map(l => l.replace(/^• /, '')).filter(Boolean).join('\n')
  }
  return {
    occ:              get('Occupancy'),
    adr:              get('ADR').replace(/^\$/, ''),
    pending:          get('Pending Arrivals'),
    arrivals:         get("Today's Arrivals"),
    departures:       get('Departures'),
    declined:         get('Declined Payments'),
    ooo:              get('Out of Order Rooms'),
    ooo_detail:       getBullets('Out of Order Room Details'),
    guest_req:        get('Guest Requests', 'Guest Request'),
    guest_req_detail: getBullets('Guest Request Details') || get('Guest Request Details'),
    refunds:          get('Rate Adjustments / Refunds', 'Rate Adjustments/Refunds'),
    maint_passdown:   getBullets('Maintenance / Passdown') || get('Maintenance / Passdown'),
    handoff_note:     get('Handoff Note'),
  }
}

function stripBold(text) {
  return String(text || '').replace(/\*\*/g, '').trim()
}

function firstNonEmptyLine(text) {
  return String(text || '')
    .split('\n')
    .map(line => line.trim())
    .find(Boolean) || ''
}

function getLineValue(text, label) {
  const escaped = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = String(text || '').match(new RegExp(`(?:^|\\n)(?:\\*\\*)?${escaped}(?:\\*\\*)?:\\s*([^\\n]+)`, 'i'))
  return (match?.[1] || '').trim()
}

function getCompletedSummary(text) {
  const match = String(text || '').match(/(?:^|\n)[•-]\s*Completed:\s*([^\n]+)/i)
  return match?.[1]?.trim() || ''
}

function getChecklistSummary(text) {
  return getLineValue(text, 'Checklist') || getCompletedSummary(text)
}

function getIncompleteTasks(text) {
  const match = String(text || '').match(/(?:^|\n)Incomplete tasks(?:\s*\(\d+\))?:\s*([^\n]+)/i)
  if (!match?.[1]) return []
  return match[1]
    .split(/\s*;\s*/)
    .map(item => item.trim())
    .filter(Boolean)
}

function hasValue(value) {
  const normalized = String(value ?? '').trim()
  return normalized !== '' && normalized !== '—' && normalized !== '0'
}

function pushTable(lines, title, headers, rows) {
  if (!rows.length) return
  lines.push(`### ${title}`)
  lines.push(`| ${headers.join(' | ')} |`)
  lines.push(`| ${headers.map(() => '---').join(' | ')} |`)
  rows.forEach(row => lines.push(`| ${row.join(' | ')} |`))
  lines.push('')
  lines.push('---')
  lines.push('')
}

function pushBulletSection(lines, title, value) {
  if (!value) return
  lines.push(`**${title}:**`)
  value
    .split('\n')
    .map(line => line.trim())
    .filter(Boolean)
    .forEach(line => lines.push(`- ${line}`))
  lines.push('')
}

function buildLegacyNightAuditPreview(text) {
  const parsed = parseNightAuditFromPostText(text)
  const titleLine = stripBold(firstNonEmptyLine(text)).replace(/\s*[•·]\s*/g, ' — ')
  const title = titleLine.startsWith('🌙') ? titleLine : `🌙 ${titleLine || 'Night Audit Shift Log'}`
  const agentName = getLineValue(text, 'Front Desk Agent')
  const completed = getCompletedSummary(text)
  const lines = [`## ${title}`]

  if (agentName) lines.push(`**Front Desk Agent:** ${agentName}`)
  lines.push('', '---', '')

  pushTable(lines, '📊 Hotel Statistics', ['Metric', 'Start', 'End', 'New'], [
    ['Occupancy', parsed.na_occ_s, parsed.na_occ_e, parsed.na_occ_n],
    ['ADR', parsed.na_adr_s, parsed.na_adr_e, parsed.na_adr_n],
    ['RevPAR', parsed.na_revpar_s, parsed.na_revpar_e, parsed.na_revpar_n],
    ["Today's Departures", parsed.na_dep_s, parsed.na_dep_e, parsed.na_dep_n],
    ["Today's Arrivals", parsed.na_arr_s, parsed.na_arr_e, parsed.na_arr_n],
    ['Pending Arrivals', parsed.na_pend_s, parsed.na_pend_e, parsed.na_pend_n],
    ['Available Rooms', parsed.na_avail_s, parsed.na_avail_e, parsed.na_avail_n],
    ['Walk-In', parsed.na_walkin_s, parsed.na_walkin_e, parsed.na_walkin_n],
  ].filter(row => row.slice(1).some(hasValue)))

  pushTable(lines, '⚠️ Activity & Incidents', ['Item', 'Count'], [
    ['Declined Payments', parsed.na_declined],
    ['Out of Order Rooms', parsed.na_ooo],
    ['Walk-in Reservations', parsed.na_walkin_res],
    ['GTD No-Show', parsed.na_gtd_noshow],
    ['Cancellations', parsed.na_cancel_ct],
    ['Rate Adj/Refunds', parsed.na_rate_adj],
    ['Guest Requests', parsed.na_guest_req],
    ['Maintenance Pass', parsed.na_maint_ct],
    ['Security Onsite', parsed.na_security ? `${parsed.na_security}${parsed.na_security === 'Yes' && parsed.na_security_name ? ` — ${parsed.na_security_name}` : ''}` : ''],
  ].filter(([, value]) => hasValue(value)))

  pushBulletSection(lines, 'Out of Order Room Details', parsed.na_ooo_detail)
  pushBulletSection(lines, 'Cancellations', parsed.na_cancel_detail)
  pushBulletSection(lines, 'Guest Request Details', parsed.na_guest_req_detail)
  pushBulletSection(lines, 'Maintenance Pass', parsed.na_maint_detail)

  ;[
    ['General Comments', parsed.na_comments],
    ['Guest Issues / Incidents / Concerns', parsed.na_guest_issues],
    ['High Balances', parsed.na_high_bal],
    ['Call Outs', parsed.na_callouts],
  ].forEach(([label, value]) => {
    if (hasValue(value)) lines.push(`**${label}:** ${value}`)
  })

  if (completed) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push('---', '', '### ✅ Checklist', `Completed **${completed}**`, '')
  }

  if (parsed.manager_notes) {
    lines.push('---', '', '### 📝 Notes to Manager', parsed.manager_notes, '')
  }
  if (parsed.handoff_note) {
    lines.push('---', '', '### 🔄 Handoff Note for Morning Shift', parsed.handoff_note, '')
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()
}

function buildLegacyRegularPreview(text) {
  const parsed = parseMetaFromPostText(text)
  const shiftLabel = getLineValue(text, 'Shift')
  const dateLabel = getLineValue(text, 'Date')
  const titleLine = stripBold(firstNonEmptyLine(text)).replace(/\s*[•·]\s*/g, ' — ')
  const titleBase = shiftLabel
    ? `${shiftLabel}${dateLabel ? ` — ${dateLabel}` : ''}`
    : titleLine
  const shiftEmoji = /Morning Shift/i.test(titleBase) ? '☀️' : /Swing Shift/i.test(titleBase) ? '🌅' : ''
  const title = shiftEmoji && !titleBase.startsWith(shiftEmoji) ? `${shiftEmoji} ${titleBase}` : titleBase
  const agentName = getLineValue(text, 'Front Desk Agent')
  const checklistSummary = getChecklistSummary(text)
  const incompleteTasks = getIncompleteTasks(text)
  const lines = [`## ${title || 'Shift Log'}`]

  if (agentName) lines.push(`**Front Desk Agent:** ${agentName}`)
  lines.push('', '---', '')

  pushTable(lines, '📊 Hotel Snapshot', ['Metric', 'Value'], [
    ['Occupancy', parsed.occ],
    ['ADR', parsed.adr ? `$${parsed.adr}` : ''],
    ['Pending Arrivals', parsed.pending],
    ["Today's Arrivals", parsed.arrivals],
    ['Departures', parsed.departures],
  ].filter(([, value]) => hasValue(value)))

  pushTable(lines, '⚠️ Activity & Incidents', ['Item', 'Count'], [
    ['Declined Payments', parsed.declined],
    ['Out of Order Rooms', parsed.ooo],
    ['Guest Requests', parsed.guest_req],
    ['Rate Adjustments / Refunds', parsed.refunds],
  ].filter(([, value]) => hasValue(value)))

  pushBulletSection(lines, 'Out of Order Room Details', parsed.ooo_detail)
  pushBulletSection(lines, 'Guest Request Details', parsed.guest_req_detail)
  pushBulletSection(lines, 'Maintenance / Passdown', parsed.maint_passdown)

  if (checklistSummary) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push('---', '', '### ✅ Checklist')
    const compact = checklistSummary.match(/(\d+)\s*\/\s*(\d+)/)
    if (compact) {
      lines.push(`Completed **${compact[1]} / ${compact[2]}** tasks`)
    } else {
      lines.push(`Completed **${checklistSummary}**`)
    }
    if (incompleteTasks.length > 0) {
      lines.push('', '**Incomplete Tasks:**')
      incompleteTasks.forEach(task => lines.push(`- ${task}`))
    }
    lines.push('')
  }

  if (parsed.handoff_note) {
    lines.push('---', '', '### 🔄 Handoff Note', parsed.handoff_note, '')
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trim()
}

export function normalizePostPreviewText(text) {
  if (!text) return text
  if (String(text).includes('\n## ') || String(text).startsWith('## ')) return text
  if (isNightAuditPost(text)) return buildLegacyNightAuditPreview(text)
  if (/Morning Shift|Swing Shift/i.test(text)) return buildLegacyRegularPreview(text)
  return String(text).replace(/^• /gm, '- ')
}
